version: "3.8"
services:
  edudb:
    image: mysql
    container_name: edudb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: edudb
      MYSQL_ROOT_PASSWORD: root
    networks:
      - tuananh177
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always
    networks:
      - tuananh177
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka-edu
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - tuananh177
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  edu:
    image: "tuananh177/edu_v2:v1.1"
    container_name: EduV2
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "edu_v2"
      SPRING_DATASOURCE_URL: "jdbc:mysql://edudb:3306/edudb"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9094
      REDIS_HOST: redis-stack
      REDIS_PORT: 6379
    networks:
      - tuananh177
    depends_on:
      edudb:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis-stack:
        condition: service_healthy

networks:
  tuananh177:
    driver: "bridge"