server:
  port: 8080
spring:
  application:
    name: "edu_v2"

  datasource:
    url: jdbc:mysql://localhost:3306/edudb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

auth:
  outbound:
    identity:
      client-id: "286299218562-ur2avuo3vhf2hbsbuga3pkr27ejqhf67.apps.googleusercontent.com"
      client-secret: "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"
      redirect-uri: "http://localhost:3000/authenticate"
  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 86400 # 1 day (second)
    refreshable-duration: 2592000 # 30 day (second)
  verify:
    register-code-duration: 86400000 # 24 * 60 * 60 * 1000 = 86400000 milli  --- 1 day
    forgot-password-code-duration: 86400000 # 24 * 60 * 60 * 1000 = 86400000 milli  --- 1 day