server:
  port: 8080
spring:
  application:
    name: "edu_v2"

  datasource:
    url: jdbc:mysql://localhost:3306/edudb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

auth:
  outbound:
    identity:
      client-id: "286299218562-ur2avuo3vhf2hbsbuga3pkr27ejqhf67.apps.googleusercontent.com"
      client-secret: "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"
      redirect-uri: "http://localhost:3000/authenticate"
  jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 86400 # 1 day (second)
    refreshable-duration: 2592000 # 30 day (second)
  verify:
    register-code-duration: 86400000 # 24 * 60 * 60 * 1000 = 86400000 milli  --- 1 day
    forgot-password-code-duration: 86400000 # 24 * 60 * 60 * 1000 = 86400000 milli  --- 1 day

# Mail
brevo:
  api-key: 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

api:
  verify-register: "http://localhost:3000/verify/register?code="
  verify-forgot-password: "http://localhost:3000/users/password/edit?code="

redis:
  host: localhost
  port: 6379